name: Run Python Script Every 5 Minutes

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes
  workflow_dispatch:  # Allows manual execution

jobs:
  run-script:
    runs-on: ubuntu-latest  # Use the latest Ubuntu version

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3  # Check out the repository's code

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Use Python 3.9

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip  # Ensure pip is up-to-date
          pip install pandas selenium boto3

      - name: Debug Environment
        run: |
          echo "Python Version:"
          python --version
          echo "Installed Packages:"
          pip list
          echo "Current Directory Contents:"
          ls -la

      - name: Add Execution Permissions to Script
        run: chmod +x code.py

      - name: Run Python Script
        run: |
          python -u code.py  # Run with unbuffered output for live logs
